### ISSUE TITLE
Could not find a version that satisfies the requirement inotifications

### ISSUE THREAD

**Issue by KhagayN** [niloch/inotifications#1]
I don't think this package is installable via pip. It's not on the Python Package Index https://pypi.python.org/pypi

**Comment by niloch** [comment]
You are correct.  I'm not sure I am ready to commit a version to pypi.  I may rename the package or add more features before making it publicly available on pypi.   It is still installable from the clone wiht pip or via `python setup.py install` or by creating a distribution with `python setup.py sdist bdist_wheel` and pip installing the wheel in the `dist` directory.  Hope that helps.
